export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN = 'LOGIN';
export const LOGIN_REGISTER = 'LOGIN_REGISTER'
export const LOGIN_INITIALIZE = 'LOGIN_INITIALIZE';