export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN = 'LOGIN';
export const LOGIN_REGISTER = 'LOGIN_REGISTER'
export const LOGIN_INITIALIZE = 'LOGIN_INITIALIZE';
export const FORM_TYPE =  {Login: 'Login', Registration: 'Registration'};
export const UPDATE_MOBILE_NUMBER = 'UPDATE_MOBILE_NUMBER';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_PASSWORD = 'SET_PASSWORD';
